[package]
name = "gb-debug"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
eframe = "0.31"
egui_tiles = "0.12"
native-dialog = "0.7"
anyhow = "1.0.9"
blip_buf = ">=0.1.3"
cpal = "0.15"

env_logger = "0.11"
log = "0.4"
