use std::fmt::{Display, Formatter};

pub enum Licensee {
    Nintento,
    Capcom,
    HOTB,
    Jaleco,
    CoconutsJapan,
    EliteSystems,
    ElectronicArts,
    HudsonSoft,
    ITCEntertainment,
    Yanoman,
    JapanClary,
    VirginGamesLtd,
    PCMComplete,
    SanX,
    Kemco,
    SETACorporation,
    Infogrames,
    Nintendo,
    Bandai,
    Konami,
    HectorSoft,
    Banpresto,
    EntertainmentInteractive,
    Gremlin,
    UbiSoft,
    Atlus,
    MalibuInteractive,
    Angel,
    SpectrumHolobyte,
    Irem,
    USGold,
    Absolute,
    AcclaimEntertainment,
    Activision,
    SammyUSACorporation,
    GameTek,
    ParkPlace,
    LJN,
    Matchbox,
    MiltonBradleyCompany,
    Mindscape,
    Romstar,
    NaxatSoft,
    Tradewest,
    TitusInteractive,
    OceanSoftware,
    ElectroBrain,
    InterplayEntertainment,
    Broderbund,
    SculpturedSoftware,
    TheSalesCurveLimited,
    THQ,
    Accolade,
    TriffixEntertainment,
    MicroProse,
    MisawaEntertainment,
    LOZCG,
    TokumaShoten,
    BulletProofSoftware,
    VicTokaiCorp,
    ApeInc,
    IMax,
    ChunsoftCo,
    VideoSystem,
    TsubarayaProductions,
    Varie,
    YonezawaSPal,
    Arc,
    NihonBussan,
    Tecmo,
    Imagineer,
    Nova,
    HoriElectric,
    Kawada,
    Takara,
    TechnosJapan,
    ToeiAnimation,
    Toho,
    Namco,
    ASCIICorporation,
    SquareEnix,
    HALLaboratory,
    SNK,
    PonyCanyon,
    CultureBrain,
    Sunsoft,
    SonyImagesoft,
    SammyCorporation,
    Taito,
    Square,
    DataEast,
    TonkinHouse,
    Koei,
    UFL,
    UltraGames,
    VAPInc,
    UseCorporation,
    Meldac,
    SoftwareEngineeringLab,
    Quest,
    SigmaEnterprises,
    AskKodanshaCo,
    CopyaSystem,
    Tomy,
    NipponComputerSystems,
    HumanEnt,
    Altron,
    TowaChiki,
    Yutaka,
    Epoch,
    Athena,
    AsmilkAceEnterainment,
    Natsume,
    KingRecords,
    EpicSonyRecords,
    IGS,
    AWave,
    ExtremeEntertainment,

    None,
    NintentoResearchDevelopment,
    BAI,
    KSS,
    PlanningOfficeWADA,
    SetaCorporation,
    Viacom,
    OceanAcclaim,
    HiTechExpressions,
    Mattel,
    MiltonBradleyCorporation,
    TitusInteractiveLtd,
    LucasfilmGames,
    InterplayEnterainment,
    Lozc,
    TsukudaOriginal,
    Kaneko,
    PackInVideo,
    BottomUp,
    MTO,
    Kodansha,
}

impl Display for Licensee {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        match self {
            Licensee::None => write!(f, "None"),
            Licensee::Nintento => write!(f, "Nintendo"),
            Licensee::Capcom => write!(f, "Capcom"),
            Licensee::HOTB => write!(f, "HOT-B"),
            Licensee::Jaleco => write!(f, "Jaleco"),
            Licensee::CoconutsJapan => write!(f, "Coconuts Japan"),
            Licensee::EliteSystems => write!(f, "Elite Systems"),
            Licensee::ElectronicArts => write!(f, "Electronic Arts"),
            Licensee::HudsonSoft => write!(f, "Hudson Soft"),
            Licensee::ITCEntertainment => write!(f, "ITC Entertainment"),
            Licensee::Yanoman => write!(f, "Yanoman"),
            Licensee::JapanClary => write!(f, "Japan Clary"),
            Licensee::VirginGamesLtd => write!(f, "Virgin Games Ltd."),
            Licensee::PCMComplete => write!(f, "PCM Complete"),
            Licensee::SanX => write!(f, "San-X"),
            Licensee::Kemco => write!(f, "Kemco"),
            Licensee::SETACorporation => write!(f, "SETA Corporation"),
            Licensee::Infogrames => write!(f, "Infogrames"),
            Licensee::Nintendo => write!(f, "Nintendo"),
            Licensee::Bandai => write!(f, "Bandai"),

            Licensee::Konami => write!(f, "Konami"),
            Licensee::HectorSoft => write!(f, "Hector Soft"),
            // capcom again
            Licensee::Banpresto => write!(f, "Banpresto"),
            Licensee::EntertainmentInteractive => write!(f, "Entertainment Interactive (stub)"),
            Licensee::Gremlin => write!(f, "Gremlin"),
            Licensee::UbiSoft => write!(f, "Ubi Soft"),
            Licensee::Atlus => write!(f, "Atlus"),
            Licensee::MalibuInteractive => write!(f, "Malibu Interactive"),
            Licensee::Angel => write!(f, "Angel"),
            Licensee::SpectrumHolobyte => write!(f, "Spectrum Holobyte"),
            Licensee::Irem => write!(f, "Irem"),
            // virgin games ltd again
            // malibu interactive again
            Licensee::USGold => write!(f, "US Gold"),
            Licensee::Absolute => write!(f, "Absolute"),
            Licensee::AcclaimEntertainment => write!(f, "Acclaim Entertainment"),
            Licensee::Activision => write!(f, "Activision"),
            Licensee::SammyUSACorporation => write!(f, "Sammy USA Corporation"),
            Licensee::GameTek => write!(f, "GameTek"),
            Licensee::ParkPlace => write!(f, "Park Place"),
            Licensee::LJN => write!(f, "LJN"),
            Licensee::Matchbox => write!(f, "Matchbox"),
            Licensee::MiltonBradleyCompany => write!(f, "Milton Bradley Company"),
            Licensee::Mindscape => write!(f, "Mindscape"),
            Licensee::Romstar => write!(f, "Romstar"),
            Licensee::NaxatSoft => write!(f, "Naxat Soft"),
            Licensee::Tradewest => write!(f, "Tradewest"),
            Licensee::TitusInteractive => write!(f, "Titus Interactive"),
            // virgin games ltd again
            Licensee::OceanSoftware => write!(f, "Ocean Software"),
            // electronic arts again
            // elite systems again
            Licensee::ElectroBrain => write!(f, "Electro Brain"),
            // infogrames again
            Licensee::InterplayEntertainment => write!(f, "Interplay Entertainment"),
            Licensee::Broderbund => write!(f, "Broderbund"),
            Licensee::SculpturedSoftware => write!(f, "Sculptured Software"),
            Licensee::TheSalesCurveLimited => write!(f, "The Sales Curve Limited"),
            Licensee::THQ => write!(f, "THQ"),
            Licensee::Accolade => write!(f, "Accolade"),
            Licensee::TriffixEntertainment => write!(f, "Triffix Entertainment"),
            Licensee::MicroProse => write!(f, "MicroProse"),
            // kemco again
            Licensee::MisawaEntertainment => write!(f, "Misawa Entertainment"),
            Licensee::LOZCG => write!(f, "LOZC G."),
            Licensee::TokumaShoten => write!(f, "Tokuma Shoten"),
            Licensee::BulletProofSoftware => write!(f, "Bullet-Proof Software"),
            Licensee::VicTokaiCorp => write!(f, "Vic Tokai Corp."),
            Licensee::ApeInc => write!(f, "Ape Inc."),
            Licensee::IMax => write!(f, "I'Max"),
            Licensee::ChunsoftCo => write!(f, "Chunsoft Co."),
            Licensee::VideoSystem => write!(f, "Video System"),
            Licensee::TsubarayaProductions => write!(f, "Tsubaraya Productions"),
            Licensee::Varie => write!(f, "Varie"),
            Licensee::YonezawaSPal => write!(f, "Yonezawa/s'pal"),
            // kemco again
            Licensee::Arc => write!(f, "Arc"),
            Licensee::NihonBussan => write!(f, "Nihon Bussan"),
            Licensee::Tecmo => write!(f, "Tecmo"),
            Licensee::Imagineer => write!(f, "Imagineer"),
            // banpresto again
            Licensee::Nova => write!(f, "Nova"),
            Licensee::HoriElectric => write!(f, "Hori Electric"),
            // bandai again
            // konami again
            Licensee::Kawada => write!(f, "Kawada"),
            Licensee::Takara => write!(f, "Takara"),
            Licensee::TechnosJapan => write!(f, "Technos Japan"),
            Licensee::ToeiAnimation => write!(f, "Toei Animation"),
            Licensee::Toho => write!(f, "Toho"),
            Licensee::Namco => write!(f, "Namco"),
            // acclaim entertainment again
            Licensee::ASCIICorporation => write!(f, "ASCII Corporation"),
            // bandai again
            Licensee::SquareEnix => write!(f, "Square Enix"),
            Licensee::HALLaboratory => write!(f, "HAL Laboratory"),
            Licensee::SNK => write!(f, "SNK"),
            Licensee::PonyCanyon => write!(f, "Pony Canyon"),
            Licensee::CultureBrain => write!(f, "Culture Brain"),
            Licensee::Sunsoft => write!(f, "Sunsoft"),
            Licensee::SonyImagesoft => write!(f, "Sony Imagesoft"),
            Licensee::SammyCorporation => write!(f, "Sammy Corporation"),
            Licensee::Taito => write!(f, "Taito"),
            Licensee::Square => write!(f, "Square"),
            // tokuma shoten again
            Licensee::DataEast => write!(f, "Data East"),
            Licensee::TonkinHouse => write!(f, "Tonkin House"),
            Licensee::Koei => write!(f, "Koei"),
            Licensee::UFL => write!(f, "UFL"),
            Licensee::UltraGames => write!(f, "Ultra Games"),
            Licensee::VAPInc => write!(f, "VAP Inc."),
            Licensee::UseCorporation => write!(f, "Use Corporation"),
            Licensee::Meldac => write!(f, "Meldac"),
            // pony canyon again
            // angel again
            // taito again
            Licensee::SoftwareEngineeringLab => write!(f, "SOFEL (Software Engineering Lab)"),
            Licensee::Quest => write!(f, "Quest"),
            Licensee::SigmaEnterprises => write!(f, "Sigma Enterprises"),
            Licensee::AskKodanshaCo => write!(f, "Ask Kodansha Co."),
            // naxat soft again
            Licensee::CopyaSystem => write!(f, "Copya System"),
            Licensee::Tomy => write!(f, "Tomy"),
            // ljn again
            Licensee::NipponComputerSystems => write!(f, "Nippon Computer Systems"),
            Licensee::HumanEnt => write!(f, "Human Ent."),
            Licensee::Altron => write!(f, "Altron"),
            // jaleco again
            Licensee::TowaChiki => write!(f, "Towa Chiki"),
            Licensee::Yutaka => write!(f, "Yutaka"),
            // varie again
            Licensee::Epoch => write!(f, "Epoch"),
            Licensee::Athena => write!(f, "Athena"),
            Licensee::AsmilkAceEnterainment => write!(f, "Asmik Ace Enterainment"),
            Licensee::Natsume => write!(f, "Natsume"),
            Licensee::KingRecords => write!(f, "King Records"),
            Licensee::EpicSonyRecords => write!(f, "Epic/Sony Records"),
            Licensee::IGS => write!(f, "IGS"),
            Licensee::AWave => write!(f, "A Wave"),
            Licensee::ExtremeEntertainment => write!(f, "Extreme Entertainment"),
            // ljn again

            // new licensees
            Licensee::NintentoResearchDevelopment => write!(f, "Nintento Research & Development"),
            // capcom again
            // electronic arts again
            Licensee::BAI => write!(f, "B-AI"),
            Licensee::KSS => write!(f, "KSS"),
            Licensee::PlanningOfficeWADA => write!(f, "Planning Office WADA"),
            // pcm complete again
            // san-x again
            // kemco again
            Licensee::SetaCorporation => write!(f, "Seta Corporation"),
            Licensee::Viacom => write!(f, "Viacom"),
            // nintendo again
            // bandai again
            Licensee::OceanAcclaim => write!(f, "Ocean Software/Acclaim Entertainment"),
            // konami again
            // hector soft again
            // taito again
            // hudson soft again
            // banpresto again
            // ubi soft again
            // atlus again
            // malibu interactive again
            // angel again
            // bullet proof software again
            // irem again
            // absolute again
            // acclaim entertainment again
            // activision again
            // sammy usa corporation again
            // konami again
            Licensee::HiTechExpressions => write!(f, "Hi Tech Expressions"),
            // ljn again
            // matchbox again
            Licensee::Mattel => write!(f, "Mattel"),
            Licensee::MiltonBradleyCorporation => write!(f, "Milton Bradley Corporation"),
            Licensee::TitusInteractiveLtd => write!(f, "Titus Interactive Ltd"),
            // virgin games ltd again
            Licensee::LucasfilmGames => write!(f, "Lucasfilm Games"),
            // ocean software again
            // electronic arts again
            // infogrames again
            Licensee::InterplayEnterainment => write!(f, "Interplay Enterainment"),
            // broderbund again
            // sculptured software again
            // the sales curve limited again
            // thq again
            // accolade again
            // misawa entertainment again
            Licensee::Lozc => write!(f, "Lozc"),
            // tokuma shoten again
            Licensee::TsukudaOriginal => write!(f, "Tsukuda Original"),
            // chunsoft co again
            // video system again
            // varie again
            // yonezawa/s'pal again
            Licensee::Kaneko => write!(f, "Kaneko"),
            Licensee::PackInVideo => write!(f, "Pack-In-Video"),
            Licensee::BottomUp => write!(f, "Bottom Up"),
            Licensee::MTO => write!(f, "MTO"),
            Licensee::Kodansha => write!(f, "Kodansha"),
        }
    }
}

pub fn from_new_code(code: &str) -> Option<Licensee> {
    match code {
        "00" => Some(Licensee::None),
        "01" => Some(Licensee::NintentoResearchDevelopment),
        "08" => Some(Licensee::Capcom),
        "13" => Some(Licensee::ElectronicArts),
        "18" => Some(Licensee::HudsonSoft),
        "19" => Some(Licensee::BAI),
        "20" => Some(Licensee::KSS),
        "22" => Some(Licensee::PlanningOfficeWADA),
        "24" => Some(Licensee::PCMComplete),
        "25" => Some(Licensee::SanX),
        "28" => Some(Licensee::Kemco),
        "29" => Some(Licensee::SetaCorporation),
        "30" => Some(Licensee::Viacom),
        "31" => Some(Licensee::Nintendo),
        "32" => Some(Licensee::Bandai),
        "33" => Some(Licensee::OceanAcclaim),
        "34" => Some(Licensee::Konami),
        "35" => Some(Licensee::HectorSoft),
        "36" => Some(Licensee::Taito),
        "37" => Some(Licensee::HudsonSoft),
        "39" => Some(Licensee::Banpresto),
        "41" => Some(Licensee::UbiSoft),
        "42" => Some(Licensee::Atlus),
        "44" => Some(Licensee::MalibuInteractive),
        "46" => Some(Licensee::Angel),
        "47" => Some(Licensee::BulletProofSoftware),
        "49" => Some(Licensee::Irem),
        "50" => Some(Licensee::Absolute),
        "51" => Some(Licensee::AcclaimEntertainment),
        "52" => Some(Licensee::Activision),
        "53" => Some(Licensee::SammyUSACorporation),
        "54" => Some(Licensee::Konami),
        "55" => Some(Licensee::HiTechExpressions),
        "56" => Some(Licensee::LJN),
        "57" => Some(Licensee::Matchbox),
        "58" => Some(Licensee::Mattel),
        "59" => Some(Licensee::MiltonBradleyCorporation),
        "60" => Some(Licensee::TitusInteractiveLtd),
        "61" => Some(Licensee::VirginGamesLtd),
        "64" => Some(Licensee::LucasfilmGames),
        "67" => Some(Licensee::OceanSoftware),
        "69" => Some(Licensee::ElectronicArts),
        "70" => Some(Licensee::Infogrames),
        "71" => Some(Licensee::InterplayEnterainment),
        "72" => Some(Licensee::Broderbund),
        "73" => Some(Licensee::SculpturedSoftware),
        "75" => Some(Licensee::TheSalesCurveLimited),
        "78" => Some(Licensee::THQ),
        "79" => Some(Licensee::Accolade),
        "80" => Some(Licensee::MisawaEntertainment),
        "83" => Some(Licensee::Lozc),
        "86" => Some(Licensee::TokumaShoten),
        "87" => Some(Licensee::TsukudaOriginal),
        "91" => Some(Licensee::ChunsoftCo),
        "92" => Some(Licensee::VideoSystem),
        "93" => Some(Licensee::OceanAcclaim),
        "95" => Some(Licensee::Varie),
        "96" => Some(Licensee::YonezawaSPal),
        "97" => Some(Licensee::Kaneko),
        "99" => Some(Licensee::PackInVideo),
        "9H" => Some(Licensee::BottomUp),
        "A4" => Some(Licensee::Konami),
        "BL" => Some(Licensee::MTO),
        "DK" => Some(Licensee::Kodansha),
        _ => None,
    }
}

pub fn from_old_code(code: u8) -> Option<Licensee> {
    match code {
        0x00 => Some(Licensee::None),
        0x01 => Some(Licensee::Nintento),
        0x08 => Some(Licensee::Capcom),
        0x09 => Some(Licensee::HOTB),
        0x0A => Some(Licensee::Jaleco),
        0x0B => Some(Licensee::CoconutsJapan),
        0x0C => Some(Licensee::EliteSystems),
        0x13 => Some(Licensee::ElectronicArts),
        0x18 => Some(Licensee::HudsonSoft),
        0x19 => Some(Licensee::ITCEntertainment),
        0x1A => Some(Licensee::Yanoman),
        0x1D => Some(Licensee::JapanClary),
        0x1F => Some(Licensee::VirginGamesLtd),
        0x24 => Some(Licensee::PCMComplete),
        0x25 => Some(Licensee::SanX),
        0x28 => Some(Licensee::Kemco),
        0x29 => Some(Licensee::SETACorporation),
        0x30 => Some(Licensee::Infogrames),
        0x31 => Some(Licensee::Nintendo),
        0x32 => Some(Licensee::Bandai),
        // 33 signals a new license code
        0x34 => Some(Licensee::Konami),
        0x35 => Some(Licensee::HectorSoft),
        0x38 => Some(Licensee::Capcom),
        0x39 => Some(Licensee::Banpresto),
        0x3C => Some(Licensee::EntertainmentInteractive),
        0x3E => Some(Licensee::Gremlin),
        0x41 => Some(Licensee::UbiSoft),
        0x42 => Some(Licensee::Atlus),
        0x44 => Some(Licensee::MalibuInteractive),
        0x46 => Some(Licensee::Angel),
        0x47 => Some(Licensee::SpectrumHolobyte),
        0x49 => Some(Licensee::Irem),
        0x4A => Some(Licensee::VirginGamesLtd),
        0x4D => Some(Licensee::MalibuInteractive),
        0x4F => Some(Licensee::USGold),
        0x50 => Some(Licensee::Absolute),
        0x51 => Some(Licensee::AcclaimEntertainment),
        0x52 => Some(Licensee::Activision),
        0x53 => Some(Licensee::SammyUSACorporation),
        0x54 => Some(Licensee::GameTek),
        0x55 => Some(Licensee::ParkPlace),
        0x56 => Some(Licensee::LJN),
        0x57 => Some(Licensee::Matchbox),
        0x59 => Some(Licensee::MiltonBradleyCompany),
        0x5A => Some(Licensee::Mindscape),
        0x5B => Some(Licensee::Romstar),
        0x5C => Some(Licensee::NaxatSoft),
        0x5D => Some(Licensee::Tradewest),
        0x60 => Some(Licensee::TitusInteractive),
        0x61 => Some(Licensee::VirginGamesLtd),
        0x67 => Some(Licensee::OceanSoftware),
        0x69 => Some(Licensee::ElectronicArts),
        0x6E => Some(Licensee::EliteSystems),
        0x6F => Some(Licensee::ElectroBrain),
        0x70 => Some(Licensee::Infogrames),
        0x71 => Some(Licensee::InterplayEntertainment),
        0x72 => Some(Licensee::Broderbund),
        0x73 => Some(Licensee::SculpturedSoftware),
        0x75 => Some(Licensee::TheSalesCurveLimited),
        0x78 => Some(Licensee::THQ),
        0x79 => Some(Licensee::Accolade),
        0x7A => Some(Licensee::TriffixEntertainment),
        0x7C => Some(Licensee::MicroProse),
        0x7F => Some(Licensee::Kemco),
        0x80 => Some(Licensee::MisawaEntertainment),
        0x83 => Some(Licensee::LOZCG),
        0x86 => Some(Licensee::TokumaShoten),
        0x8B => Some(Licensee::BulletProofSoftware),
        0x8C => Some(Licensee::VicTokaiCorp),
        0x8E => Some(Licensee::ApeInc),
        0x8F => Some(Licensee::IMax),
        0x91 => Some(Licensee::ChunsoftCo),
        0x92 => Some(Licensee::VideoSystem),
        0x93 => Some(Licensee::TsubarayaProductions),
        0x95 => Some(Licensee::Varie),
        0x96 => Some(Licensee::YonezawaSPal),
        0x97 => Some(Licensee::Kemco),
        0x99 => Some(Licensee::Arc),
        0x9A => Some(Licensee::NihonBussan),
        0x9B => Some(Licensee::Tecmo),
        0x9C => Some(Licensee::Imagineer),
        0x9D => Some(Licensee::Banpresto),
        0x9F => Some(Licensee::Nova),
        0xA1 => Some(Licensee::HoriElectric),
        0xA2 => Some(Licensee::Bandai),
        0xA4 => Some(Licensee::Konami),
        0xA6 => Some(Licensee::Kawada),
        0xA7 => Some(Licensee::Takara),
        0xA9 => Some(Licensee::TechnosJapan),
        0xAA => Some(Licensee::Broderbund),
        0xAC => Some(Licensee::ToeiAnimation),
        0xAD => Some(Licensee::Toho),
        0xAF => Some(Licensee::Namco),
        0xB0 => Some(Licensee::AcclaimEntertainment),
        0xB1 => Some(Licensee::ASCIICorporation),
        0xB2 => Some(Licensee::Bandai),
        0xB4 => Some(Licensee::SquareEnix),
        0xB6 => Some(Licensee::HALLaboratory),
        0xB7 => Some(Licensee::SNK),
        0xB9 => Some(Licensee::PonyCanyon),
        0xBA => Some(Licensee::CultureBrain),
        0xBB => Some(Licensee::Sunsoft),
        0xBD => Some(Licensee::SonyImagesoft),
        0xBF => Some(Licensee::SammyCorporation),
        0xC0 => Some(Licensee::Taito),
        0xC2 => Some(Licensee::Kemco),
        0xC3 => Some(Licensee::Square),
        0xC4 => Some(Licensee::TokumaShoten),
        0xC5 => Some(Licensee::DataEast),
        0xC6 => Some(Licensee::TonkinHouse),
        0xC8 => Some(Licensee::Koei),
        0xC9 => Some(Licensee::UFL),
        0xCA => Some(Licensee::UltraGames),
        0xCB => Some(Licensee::VAPInc),
        0xCC => Some(Licensee::UseCorporation),
        0xCD => Some(Licensee::Meldac),
        0xCE => Some(Licensee::PonyCanyon),
        0xCF => Some(Licensee::Angel),
        0xD0 => Some(Licensee::Taito),
        0xD1 => Some(Licensee::SoftwareEngineeringLab),
        0xD2 => Some(Licensee::Quest),
        0xD3 => Some(Licensee::SigmaEnterprises),
        0xD4 => Some(Licensee::AskKodanshaCo),
        0xD6 => Some(Licensee::NaxatSoft),
        0xD7 => Some(Licensee::CopyaSystem),
        0xD9 => Some(Licensee::Banpresto),
        0xDA => Some(Licensee::Tomy),
        0xDB => Some(Licensee::LJN),
        0xDD => Some(Licensee::NipponComputerSystems),
        0xDE => Some(Licensee::HumanEnt),
        0xDF => Some(Licensee::Altron),
        0xE0 => Some(Licensee::Jaleco),
        0xE1 => Some(Licensee::TowaChiki),
        0xE2 => Some(Licensee::Yutaka),
        0xE3 => Some(Licensee::Varie),
        0xE5 => Some(Licensee::Epoch),
        0xE7 => Some(Licensee::Athena),
        0xE8 => Some(Licensee::AsmilkAceEnterainment),
        0xE9 => Some(Licensee::Natsume),
        0xEA => Some(Licensee::KingRecords),
        0xEB => Some(Licensee::Atlus),
        0xEC => Some(Licensee::EpicSonyRecords),
        0xEE => Some(Licensee::IGS),
        0xF0 => Some(Licensee::AWave),
        0xF3 => Some(Licensee::ExtremeEntertainment),
        0xFF => Some(Licensee::LJN),
        _ => None,
    }
}
